from __future__ import annotations

import pandas as pd

from src.forecasting.evaluation import (
    evaluate_forecast,
    compare_models,
    select_best_model,
)


def evaluate_model_predictions(
    actual,
    predicted,
    model_name: str,
) -> dict:
    """Evaluate predictions generated by one model."""

    metrics = evaluate_forecast(
        actual,
        predicted,
    )

    metrics["model_name"] = model_name
    metrics["rows_evaluated"] = len(actual)

    return metrics


def compare_prophet_and_lightgbm(
    actual,
    prophet_predictions,
    lightgbm_predictions,
) -> pd.DataFrame:
    """Compare Prophet and LightGBM performance."""

    prophet_metrics = evaluate_model_predictions(
        actual=actual,
        predicted=prophet_predictions,
        model_name="Prophet",
    )

    lightgbm_metrics = evaluate_model_predictions(
        actual=actual,
        predicted=lightgbm_predictions,
        model_name="LightGBM",
    )

    return compare_models(
        [
            prophet_metrics,
            lightgbm_metrics,
        ],
        ranking_metric="wape",
    )


def get_best_forecasting_model(
    comparison: pd.DataFrame,
) -> str:
    """Return the best forecasting model."""

    return select_best_model(
        comparison,
        ranking_metric="wape",
    )


def create_model_comparison_report(
    metrics: list[dict],
) -> dict:
    """Create a final model comparison report."""

    comparison = compare_models(
        metrics,
        ranking_metric="wape",
    )

    best_model = get_best_forecasting_model(
        comparison
    )

    return {
        "comparison": comparison,
        "best_model": best_model,
        "ranking_metric": "wape",
    }


def validate_model_comparison(
    comparison: pd.DataFrame,
) -> None:
    """Validate model comparison results."""

    required_columns = {
        "model_name",
        "mae",
        "rmse",
        "mape",
        "wape",
    }

    missing = required_columns - set(
        comparison.columns
    )

    if missing:
        raise ValueError(
            f"Missing comparison columns: "
            f"{sorted(missing)}"
        )

    if comparison.empty:
        raise ValueError(
            "Model comparison cannot be empty."
        )

    if comparison["wape"].isna().any():
        raise ValueError(
            "Model comparison contains null WAPE values."
        )

    if (
        comparison["wape"] < 0
    ).any():
        raise ValueError(
            "WAPE cannot contain negative values."
        )
    